#!/usr/bin/env node
// Generates config.js from .env (local) and/or process.env (GitHub Actions).
// process.env wins over .env so CI variables/secrets override the local file.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';

const env = {};
if (existsSync('.env')) {
  for (const line of readFileSync('.env', 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && !line.trim().startsWith('#')) env[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}
for (const k of Object.keys(process.env)) if (process.env[k] !== '') env[k] = process.env[k];

const need = (k) => { if (!env[k]) { console.error(`Missing ${k} (set it in .env or as a repo variable)`); process.exit(1); } return env[k]; };

const pin = (env.APP_PIN || '').trim();
if (pin && !/^\d{4}$/.test(pin)) { console.error('APP_PIN must be exactly 4 digits (or empty to disable).'); process.exit(1); }

const config = {
  baseUrl: need('INVOKE_URL').replace(/\/+$/, ''),
  appTitle: env.APP_TITLE || 'Imagine',
  pinHash: pin ? createHash('sha256').update(pin).digest('hex') : '',
  defaultModel: env.DEFAULT_MODEL || '',
  maxSize: Number(env.MAX_SIZE || 1024),
  pollMs: Number(env.POLL_MS || 1500),
};

writeFileSync('config.js', `// Generated by scripts/build-config.mjs — do not edit, edit .env instead.\nwindow.INVOKE_CONFIG = ${JSON.stringify(config, null, 2)};\n`);
console.log(`config.js written for ${config.baseUrl} (PIN ${pin ? 'enabled' : 'disabled'})`);
