#!/usr/bin/env node
// Generates config.js from .env (local) and/or process.env (GitHub Actions).
// process.env wins over .env so CI variables/secrets override the local file.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const env = {};
if (existsSync('.env')) {
  for (const line of readFileSync('.env', 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && !line.trim().startsWith('#')) env[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}
for (const k of Object.keys(process.env)) if (process.env[k] !== '') env[k] = process.env[k];

const need = (k) => { if (!env[k]) { console.error(`Missing ${k} (set it in .env or as a repo variable)`); process.exit(1); } return env[k]; };

const config = {
  baseUrl: need('INVOKE_URL').replace(/\/+$/, ''),
  appTitle: env.APP_TITLE || 'Imagine',
  defaultModel: env.DEFAULT_MODEL || '',
  maxSize: Number(env.MAX_SIZE || 1024),
  pollMs: Number(env.POLL_MS || 1500),
};

// Cache-busting: stamp asset URLs in index.html with the commit (CI) or the time (local) so phones fetch fresh files.
const build = (env.GITHUB_SHA || String(Date.now())).slice(0, 10);
const html = readFileSync('index.html', 'utf8').replace(/\?v=[A-Za-z0-9]+/g, `?v=${build}`);
writeFileSync('index.html', html);
config.build = build;

writeFileSync('config.js', `// Generated by scripts/build-config.mjs — do not edit, edit .env instead.\nwindow.INVOKE_CONFIG = ${JSON.stringify(config, null, 2)};\n`);
console.log(`config.js written for ${config.baseUrl} (build ${build})`);
